project:
  type: website
  output-dir: docs

execute:
  freeze: auto

website:
  title: "Bayesian Regression: Theory & Practice"
  sidebar:
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Overview
      - section: "01: Basics"
        contents:
          - href: 01-basics.qmd
            text: Overview
          - href: practice-sheets/01a-wrangling-plotting.qmd
            text: Wrangling & plotting
          - href: practice-sheets/01b-simple-regression.qmd
            text: Simple linear regression
      - section: "02: Priors, predictions & categorical predictors"
        contents:
          - href: 02-priorPredictives-categPredictors.qmd
            text: Overview
          - href: practice-sheets/02a-predictives.qmd
            text: Prior & posterior predictives
          - href: practice-sheets/02b-catPreds-tutorial.qmd
            text: Categorical predictors (tutorial)
          - href: practice-sheets/02c-catPreds-execises.qmd
            text: Categorical predictors (hands-on)
      - section: "03: Generalized linear model"
        contents:
          - href: practice-sheets/03a-GLM-tutorial.qmd
            text: GLM (tutorial)
          - href: practice-sheets/03b-GLM-exercises.qmd
            text: GLM (exercises)
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
