project:
  type: website

website:
  title: "BayesReg-2023"
  sidebar:
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Overview
      - section: "01: Basics"
        contents:
          - href: 01-basics.qmd
            text: BDA & regression
          - href: practice-sheets/01-wrangle-plot-regress.qmd
            text: Practice sheet 1
      - section: "02: priors & categorical predictors"
        contents:
          - href: 02-priorPredictives-categPredictors.qmd
            text: priors, predictions, & categorical predictors
          - href: practice-sheets/02-pregression-factors.qmd
            text: Practice sheet 2

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



